# Generated by Django 5.2 on 2025-04-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_book_cover_image_alter_borrowrecord_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='available_copies',
            field=models.PositiveIntegerField(),
        ),
    ]
