# Generated by Django 5.2 on 2025-04-22 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_book_available_copies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 6, 16, 47, 21, 519857, tzinfo=datetime.timezone.utc)),
        ),
    ]
