# Generated by Django 5.2 on 2025-04-24 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_borrowrecord_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 8, 12, 33, 31, 929968, tzinfo=datetime.timezone.utc)),
        ),
    ]
