# Generated by Django 5.2 on 2025-04-24 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_borrowrecord_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 8, 14, 50, 7, 559020, tzinfo=datetime.timezone.utc)),
        ),
    ]
