# Generated by Django 5.2 on 2025-05-07 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_borrowrecord_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 18, 8, 10, 355955, tzinfo=datetime.timezone.utc)),
        ),
    ]
